// templates/React/src/app/index.tsx
import React from "react";

import "./index.scss";

import { Button } from "../components/button";

const App: React.FC = () => (
  <div className="container">
    <h1>FSDT Boilerplates</h1>
    <p>
      Aplicação instalada e funcionando, você já pode começar a desenvolver!
    </p>
    <Button>Exemplo de componente</Button>
  </div>
);

export default App;

// templates/Angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'FSDT Boilerplates - Angular';
}

<div class="container">
  <h1>FSDT Boilerplates</h1>
  <p>Aplicação instalada e funcionando, você já pode começar a desenvolver!</p>
  <app-button>Exemplo de componente</app-button>
</div>
